springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /auth

file-server:
  min-io:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minioadmin}
    secretKey: ${MINIO_SECRET_KEY:minioadmin}

spring:
  datasource:
    username: ${DB_USER:jand}
    password: ${DB_PASSWORD:oAko4fK1mhLAqexEvrsL2cFJhvroxAAv}
    url: ${DB_URL:jdbc:postgresql://dpg-d6t1kd7kijhs73er8mfg-a.singapore-postgres.render.com:5432/godii}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fisone-service-connection-pool
      maximum-pool-size: 300
      minimum-idle: 10
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 900000
      connection-test-query: SELECT 1
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml
    default-schema: public

  logging:
    level:
      org.hibernate: ERROR

  cloud:
    openfeign:
      client:
        config:
          keycloak:
            url: ${KEYCLOAK_URL}

app:
  feature:
    mail-enabled: false
